from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected exactly one match, found {count}")
    return text.replace(old, new, 1)

# 1. Replay registry: distinguish an injected steer whose browser is still active from one whose
# physical turn has settled. Active canonical rounds must rejoin that browser, not suppress their
# tool results and not hand the conversation off to a replacement browser.
watch_path = Path("src/adapters/chatgpt-web/codex-steering-watch.ts")
watch = watch_path.read_text()
record_anchor = '''interface InjectedSteerRecord extends CodexSteerSubmission {\n  injectedAt: number;\n  settled: boolean;\n}\n'''
record_new = record_anchor + '''\nexport type InjectedCodexSteerReplayState = "active" | "settled";\n'''
watch = replace_once(watch, record_anchor, record_new, "replay state type")
settle_anchor = '''  settleTurn(threadId: string, turnId: string, now = Date.now()): void {\n    this.prune(now);\n    for (const record of this.records) {\n      if (record.threadId === threadId && record.turnId === turnId) record.settled = true;\n    }\n  }\n\n  consumeSettledThrough'''
settle_new = '''  settleTurn(threadId: string, turnId: string, now = Date.now()): void {\n    this.prune(now);\n    for (const record of this.records) {\n      if (record.threadId === threadId && record.turnId === turnId) record.settled = true;\n    }\n  }\n\n  state(threadId: string, turnId: string, text: string, now = Date.now()): InjectedCodexSteerReplayState | undefined {\n    this.prune(now);\n    for (let index = this.records.length - 1; index >= 0; index -= 1) {\n      const record = this.records[index]!;\n      if (record.threadId !== threadId || record.turnId !== turnId || record.text !== text) continue;\n      return record.settled ? "settled" : "active";\n    }\n    return undefined;\n  }\n\n  consumeSettledThrough'''
watch = replace_once(watch, settle_anchor, settle_new, "replay state lookup")
export_anchor = '''export function markInjectedCodexSteersSettled(threadId: string, turnId: string): void {\n  injectedSteerReplayRegistry.settleTurn(threadId, turnId);\n}\n\nexport function consumeInjectedCodexSteerReplay'''
export_new = '''export function markInjectedCodexSteersSettled(threadId: string, turnId: string): void {\n  injectedSteerReplayRegistry.settleTurn(threadId, turnId);\n}\n\nexport function injectedCodexSteerReplayState(\n  threadId: string,\n  turnId: string,\n  text: string,\n): InjectedCodexSteerReplayState | undefined {\n  return injectedSteerReplayRegistry.state(threadId, turnId, text);\n}\n\nexport function consumeInjectedCodexSteerReplay'''
watch = replace_once(watch, export_anchor, export_new, "replay state export")
watch_path.write_text(watch)

# 2. Session registry: expose the one still-running owner without mutating ownership. This is the
# canonical tool-result continuation for a steer already mirrored into that exact browser.
sessions_path = Path("src/adapters/chatgpt-web/turn-execution.ts")
sessions = sessions_path.read_text()
find_anchor = '''  find(key: string): ChatGptTurnSession | undefined {\n    const session = this.entries.get(key);\n    session?.touch();\n    return session;\n  }\n'''
find_new = '''  findActiveOwner(ownerKey: string, turnId: string): { key: string; session: ChatGptTurnSession } | undefined {\n    const matches = [...this.entries].filter(([, session]) => (\n      session.ownerKey === ownerKey\n      && session.runtime.turnId === turnId\n      && session.isActive()\n    ));\n    if (matches.length > 1) {\n      throw new Error(`ChatGPT thread has ${matches.length} active browser owners for one native turn`);\n    }\n    const match = matches[0];\n    if (!match) return undefined;\n    const [key, session] = match;\n    session.touch();\n    return { key, session };\n  }\n\n  find(key: string): ChatGptTurnSession | undefined {\n    const session = this.entries.get(key);\n    session?.touch();\n    return session;\n  }\n'''
sessions = replace_once(sessions, find_anchor, find_new, "active owner lookup")
sessions_path.write_text(sessions)

# 3. Adapter routing: active mirrored steer replay joins the existing session; settled replay retains
# the cheap empty acknowledgement. A replay that claims to be active but has no active owner fails
# retryably instead of creating a duplicate browser turn.
index_path = Path("src/adapters/chatgpt-web/index.ts")
index = index_path.read_text()
import_old = '''  codexSteeringLogWatcher,\n  codexUserRevisionText,\n  consumeInjectedCodexSteerReplay,\n  markInjectedCodexSteersSettled,\n  recordInjectedCodexSteer,\n} from "./codex-steering-watch";'''
import_new = '''  codexSteeringLogWatcher,\n  codexUserRevisionText,\n  consumeInjectedCodexSteerReplay,\n  injectedCodexSteerReplayState,\n  markInjectedCodexSteersSettled,\n  recordInjectedCodexSteer,\n} from "./codex-steering-watch";'''
index = replace_once(index, import_old, import_new, "steer state import")

old_immediate = '''        const immediateSteerIdentity = extractChatGptTurnIdentity(parsed);\n        if (!parsed._compactionRequest && immediateSteerIdentity.threadId && immediateSteerIdentity.turnId) {\n          const revisionText = codexUserRevisionText(extractChatGptTurnUserRevision(parsed));\n          if (revisionText && consumeInjectedCodexSteerReplay(\n            immediateSteerIdentity.threadId,\n            immediateSteerIdentity.turnId,\n            revisionText,\n          )) {\n            console.info(`[chatgpt-web] consumed canonical Codex replay for an already mirrored steer (textChars=${revisionText.length})`);\n            emitBrowserCompletion(\n              { type: "final", answer: "" },\n              estimateChatGptWebUsage(currentUsageInput(parsed), { answer: "", reasoning: [] }, turnCapabilities),\n              emit,\n            );\n            return;\n          }\n        }'''
new_immediate = '''        const immediateSteerIdentity = extractChatGptTurnIdentity(parsed);\n        const immediateSteerRevisionText = !parsed._compactionRequest\n          && immediateSteerIdentity.threadId\n          && immediateSteerIdentity.turnId\n          ? codexUserRevisionText(extractChatGptTurnUserRevision(parsed))\n          : undefined;\n        const mirroredSteerReplayState = (): ReturnType<typeof injectedCodexSteerReplayState> => (\n          immediateSteerRevisionText\n            && immediateSteerIdentity.threadId\n            && immediateSteerIdentity.turnId\n            ? injectedCodexSteerReplayState(\n              immediateSteerIdentity.threadId,\n              immediateSteerIdentity.turnId,\n              immediateSteerRevisionText,\n            )\n            : undefined\n        );\n        const consumeSettledMirroredSteerReplay = (): boolean => Boolean(\n          immediateSteerRevisionText\n          && immediateSteerIdentity.threadId\n          && immediateSteerIdentity.turnId\n          && consumeInjectedCodexSteerReplay(\n            immediateSteerIdentity.threadId,\n            immediateSteerIdentity.turnId,\n            immediateSteerRevisionText,\n          )\n        );\n        const emitSettledMirroredSteerReplay = (): void => {\n          console.info(\n            `[chatgpt-web] consumed canonical Codex replay for an already mirrored steer`\n            + ` (textChars=${immediateSteerRevisionText?.length ?? 0})`,\n          );\n          emitBrowserCompletion(\n            { type: "final", answer: "" },\n            estimateChatGptWebUsage(currentUsageInput(parsed), { answer: "", reasoning: [] }, turnCapabilities),\n            emit,\n          );\n        };\n        if (mirroredSteerReplayState() === "settled" && consumeSettledMirroredSteerReplay()) {\n          emitSettledMirroredSteerReplay();\n          return;\n        }'''
index = replace_once(index, old_immediate, new_immediate, "immediate replay routing")

old_acquire = '''        const executionKey = `${executionNamespace}:${chatGptTurnExecutionKey(parsed)}`;\n        const ownerKey = `${executionNamespace}:${chatGptThreadOwnershipKey(parsed)}`;\n        const traceId = createHash("sha256").update(executionKey).digest("hex").slice(0, 12);\n        const identity = extractChatGptTurnIdentity(parsed);\n        const steeringConversationKey = identity.turnId\n          ? await chatGptTurnSessions.handoffActiveOwnerForSteering(\n            ownerKey,\n            identity.turnId,\n            executionKey,\n            incoming.abortSignal,\n          )\n          : undefined;\n        const session = await chatGptTurnSessions.getOrCreateAfterOwnerRetirement(\n          executionKey,\n          ownerKey,\n          () => startRuntime(parsed, environment, traceId, turnCapabilities, steeringConversationKey),\n          traceId,\n          incoming.abortSignal,\n        );'''
new_acquire = '''        const executionKey = `${executionNamespace}:${chatGptTurnExecutionKey(parsed)}`;\n        const ownerKey = `${executionNamespace}:${chatGptThreadOwnershipKey(parsed)}`;\n        const traceId = createHash("sha256").update(executionKey).digest("hex").slice(0, 12);\n        const identity = extractChatGptTurnIdentity(parsed);\n        let session: ChatGptTurnSession | undefined;\n        let ownedExecutionKey = executionKey;\n        let steeringConversationKey: string | undefined;\n\n        const replayStateAtAcquire = mirroredSteerReplayState();\n        if (replayStateAtAcquire === "settled" && consumeSettledMirroredSteerReplay()) {\n          emitSettledMirroredSteerReplay();\n          return;\n        }\n        if (replayStateAtAcquire === "active" && identity.turnId) {\n          const activeOwner = chatGptTurnSessions.findActiveOwner(ownerKey, identity.turnId);\n          if (activeOwner) {\n            session = activeOwner.session;\n            ownedExecutionKey = activeOwner.key;\n            console.info(\n              `[chatgpt-web] attached canonical Codex replay to active mirrored steer`\n              + ` (trace=${session.traceId ?? "unknown"}, textChars=${immediateSteerRevisionText?.length ?? 0})`,\n            );\n          } else {\n            // Physical settlement and registry settlement are separate microtasks. Re-check once: if\n            // the browser just finished, consume the settled replay; if it still claims active, do\n            // not start a duplicate browser while ownership is in transition.\n            await Promise.resolve();\n            if (mirroredSteerReplayState() === "settled" && consumeSettledMirroredSteerReplay()) {\n              emitSettledMirroredSteerReplay();\n              return;\n            }\n            throw new ChatGptWebAdapterError(\n              "Canonical Codex steer replay arrived while its already-mirrored browser ownership was transitioning; retry this native round without starting another browser.",\n              {\n                status: 409,\n                errorType: "invalid_request_error",\n                code: "steer_replay_owner_transition",\n                retryable: true,\n              },\n            );\n          }\n        }\n\n        if (!session) {\n          steeringConversationKey = identity.turnId\n            ? await chatGptTurnSessions.handoffActiveOwnerForSteering(\n              ownerKey,\n              identity.turnId,\n              executionKey,\n              incoming.abortSignal,\n            )\n            : undefined;\n          session = await chatGptTurnSessions.getOrCreateAfterOwnerRetirement(\n            executionKey,\n            ownerKey,\n            () => startRuntime(parsed, environment, traceId, turnCapabilities, steeringConversationKey),\n            traceId,\n            incoming.abortSignal,\n          );\n        }'''
index = replace_once(index, old_acquire, new_acquire, "active mirrored session acquisition")
index = replace_once(
    index,
    '''            chatGptTurnSessions.retire(executionKey, session);''',
    '''            chatGptTurnSessions.retire(ownedExecutionKey, session);''',
    "retire actual session key",
)
index_path.write_text(index)

# 4. Registry unit test pins the state transition that the live regression depends on.
watch_test_path = Path("tests/codex-steering-watch.test.ts")
watch_test = watch_test_path.read_text()
watch_import_old = '''  decodeRustDebugString,\n  markInjectedCodexSteersSettled,\n  parseCodexSteerSubmission,'''
watch_import_new = '''  decodeRustDebugString,\n  injectedCodexSteerReplayState,\n  markInjectedCodexSteersSettled,\n  parseCodexSteerSubmission,'''
watch_test = replace_once(watch_test, watch_import_old, watch_import_new, "watch test import")
old_test = '''test("a mirrored steer is suppressed only after its browser turn physically settles", () => {\n  resetInjectedCodexSteerReplayRegistryForTests();\n  const steer = { logId: 20, threadId, turnId, text: "new direction" };\n  recordInjectedCodexSteer(steer);\n  expect(consumeInjectedCodexSteerReplay(threadId, turnId, steer.text)).toBeFalse();\n  markInjectedCodexSteersSettled(threadId, turnId);\n  expect(consumeInjectedCodexSteerReplay(threadId, turnId, steer.text)).toBeTrue();\n  expect(consumeInjectedCodexSteerReplay(threadId, turnId, steer.text)).toBeFalse();\n});'''
new_test = '''test("a mirrored steer stays active for canonical tool-result rounds and is consumed only after physical settlement", () => {\n  resetInjectedCodexSteerReplayRegistryForTests();\n  const steer = { logId: 20, threadId, turnId, text: "new direction" };\n  recordInjectedCodexSteer(steer);\n  expect(injectedCodexSteerReplayState(threadId, turnId, steer.text)).toBe("active");\n  expect(consumeInjectedCodexSteerReplay(threadId, turnId, steer.text)).toBeFalse();\n  expect(injectedCodexSteerReplayState(threadId, turnId, steer.text)).toBe("active");\n  markInjectedCodexSteersSettled(threadId, turnId);\n  expect(injectedCodexSteerReplayState(threadId, turnId, steer.text)).toBe("settled");\n  expect(consumeInjectedCodexSteerReplay(threadId, turnId, steer.text)).toBeTrue();\n  expect(injectedCodexSteerReplayState(threadId, turnId, steer.text)).toBeUndefined();\n  expect(consumeInjectedCodexSteerReplay(threadId, turnId, steer.text)).toBeFalse();\n});'''
watch_test = replace_once(watch_test, old_test, new_test, "active replay registry test")
watch_test_path.write_text(watch_test)

# 5. Lifecycle contract test makes the exact live failure ordering impossible to regress silently.
lifecycle_path = Path("tests/chatgpt-steering-lifecycle.test.ts")
lifecycle = lifecycle_path.read_text()
lifecycle += '''\n\ntest("canonical replay of an active mirrored steer reuses its browser owner before any handoff", () => {\n  const source = readFileSync("src/adapters/chatgpt-web/index.ts", "utf8");\n  const state = source.indexOf('replayStateAtAcquire === "active"');\n  const reuse = source.indexOf("chatGptTurnSessions.findActiveOwner(ownerKey, identity.turnId)", state);\n  const attach = source.indexOf("attached canonical Codex replay to active mirrored steer", reuse);\n  const handoff = source.indexOf("chatGptTurnSessions.handoffActiveOwnerForSteering(", state);\n  expect(state).toBeGreaterThan(-1);\n  expect(reuse).toBeGreaterThan(state);\n  expect(attach).toBeGreaterThan(reuse);\n  expect(handoff).toBeGreaterThan(attach);\n  expect(source).toContain("chatGptTurnSessions.retire(ownedExecutionKey, session)");\n  expect(source).toContain("steer_replay_owner_transition");\n});\n'''
lifecycle_path.write_text(lifecycle)

print("patched active mirrored steer replay to reuse the live browser/session")
